### ISSUE TITLE
Could not connect to the mongoDB atlas server

### ISSUE THREAD

**Issue by sidC123** [sb011/instagram-clone#1]
I tried cloning the app. but server did not start on port 5000 because backend was not able to connect to the mongoDB atlas server.
Help me out here so that I can connect it to the server. My sole purpose is to understand the Like feature with react redux. 

![image](https://user-images.githubusercontent.com/76949509/210149187-69906d45-7b8e-48ad-90eb-8a893f4b41ec.png)

**Comment by sb011** [comment]
> My MongoDB Atlas is currently paused, so you must use yours. You can add your MongoDB connection string in the ".env" file. Please let me know if it does not work.

**Comment by sb011** [comment]
I believe your issue has been resolved because you haven't responded yet. I'm closing this issue because of that.
